server:
  port: 8000

spring:
  application:
    name: spring-cloud-eureka-server # 应用服务名

eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册入eureka server中心，默认true
    fetch-registry: false # 表示是否从eureka server 注册中心获取注册信息，默认true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔；
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: eureka-server

