spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ #\u4E0E\u6CE8\u518C\u4E2D\u5FC3\u7684\u4EA4\u4E92\u5730\u5740
server:
  port: 9001 # \u5206\u522B\u4E3A 9001\u30019002\u30019003
